In [59]:
import requests
from bs4 import BeautifulSoup
import json
import codecs
import random
import time
import xgboost

import tensorflow as tf
import numpy as np
from PIL import Image, ImageDraw, ImageFont
from IPython.display import display
import pymysql
import pandas as pd

import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [52]:
df = pd.read_csv("D:\\桌面\\18.1225med.csv",engine="python",index_col=0)

In [124]:
for i in range (1,100):
    X=df.iloc[:, :-1]#擷取變數項
    Y=df.iloc[:, -1].astype("category")


    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=i)
    xgbc = XGBClassifier(base_score=0.1)
    xgbc.fit(X_train, y_train)
    print(i)
    #print('The accuracy of eXtreme Gradient Boosting Classifier on testing set:', xgbc.score(X_test, y_test))
    #Y_predict=xgbc.predict(X_test)
    #C=confusion_matrix(y_test, Y_predict)
    Y_predict=xgbc.predict(XX_test)
    C=confusion_matrix(YYY_test, Y_predict)

    print(C)


1
[[612]]
2
[[612]]
3
[[  0   0]
 [  2 610]]
4
[[  0   0]
 [  2 610]]
5
[[612]]
6
[[612]]
7
[[  0   0]
 [  2 610]]
8
[[612]]
9
[[612]]
10
[[  0   0]
 [  2 610]]
11
[[  0   0]
 [  1 611]]
12
[[  0   0]
 [  4 608]]
13
[[612]]
14
[[  0   0]
 [  1 611]]
15
[[612]]
16
[[  0   0]
 [  2 610]]
17
[[612]]
18
[[  0   0]
 [  4 608]]
19
[[  0   0]
 [  1 611]]
20
[[612]]
21
[[612]]
22
[[  0   0]
 [  2 610]]
23
[[  0   0]
 [  1 611]]
24
[[  0   0]
 [  2 610]]
25
[[612]]
26
[[  0   0]
 [  1 611]]
27
[[  0   0]
 [  1 611]]
28
[[  0   0]
 [  2 610]]
29
[[  0   0]
 [  2 610]]
30
[[612]]
31
[[612]]
32
[[612]]
33
[[  0   0]
 [  1 611]]
34
[[  0   0]
 [  2 610]]
35
[[  0   0]
 [  2 610]]
36
[[  0   0]
 [  1 611]]
37
[[612]]
38
[[  0   0]
 [  1 611]]
39
[[  0   0]
 [  3 609]]
40
[[612]]
41
[[612]]
42
[[  0   0]
 [  1 611]]
43
[[  0   0]
 [  1 611]]
44
[[  0   0]
 [  1 611]]
45
[[  0   0]
 [  1 611]]
46
[[612]]
47
[[612]]
48
[[  0   0]
 [  1 611]]
49
[[  0   0]
 [  1 611]]
50
[[  0   0]
 [  1 611]]
51
[[  0 

In [90]:
from xgboost import XGBClassifier

Y_predict=xgbc.predict(X_test)


In [94]:
C=confusion_matrix(y_test, Y_predict)
C

array([[ 0, 17],
       [ 0, 89]], dtype=int64)

In [98]:
Y.value_counts(1)

1    0.871795
0    0.128205
Name: Therapy, dtype: float64

In [102]:
groupdf=df.groupby("Therapy")

In [111]:
index1=groupdf.groups[0]

In [120]:
YY_test=df.drop(index1,axis=0)

In [121]:
XX_test=YY_test.iloc[:,:-1]
YYY_test=YY_test.iloc[:,-1]
YYY_test


1      1
2      1
3      1
4      1
6      1
10     1
11     1
12     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
28     1
29     1
30     1
31     1
32     1
33     1
34     1
35     1
36     1
37     1
      ..
669    1
670    1
671    1
673    1
674    1
675    1
677    1
679    1
680    1
681    1
682    1
683    1
684    1
685    1
686    1
687    1
688    1
689    1
690    1
691    1
692    1
693    1
694    1
695    1
696    1
697    1
698    1
699    1
700    1
701    1
Name: Therapy, Length: 612, dtype: int64

In [122]:
Y_predict=xgbc.predict(XX_test)
C=confusion_matrix(YYY_test, Y_predict)
C

array([[612]], dtype=int64)

In [123]:
XX_test

性別_1  性別_2  請問您曾經照顧過術後噁心嘔吐患者之經驗嗎?_0  請問您曾經照顧過術後噁心嘔吐患者之經驗嗎?_1  \
1       1     0                        1                        0   
2       0     1                        0                        1   
3       0     1                        0                        1   
4       0     1                        1                        0   
6       0     1                        1                        0   
10      0     1                        1                        0   
11      0     1                        1                        0   
12      1     0                        1                        0   
14      0     1                        0                        1   
15      0     1                        1                        0   
16      0     1                        0                        1   
17      0     1                        0                        1   
18      0     1                        1                        0   
19      0     1                        1                        0   
20      0     1                        0                        1   
21      0     1                        1                        0   
22      0     1                        1                        0   
23      0     1                        1                        0   
24      0     1                        1                        0   
25      1     0                        1                        0   
28      0     1                        1                        0   
29      0     1                        1                        0   
30      0     1                        1                        0   
31      0     1                        1                        0   
32      0     1                        1                        0   
33      0     1                        1                        0   
34      1     0                        1                        0   
35      1     0                        1                        0   
36      0     1                        1                        0   
37      0     1                        1                        0   
..    ...   ...                      ...                      ...   
669     1     0                        1                        0   
670     0     1                        1                        0   
671     0     1                        1                        0   
673     1     0                        0                        1   
674     0     1                        1                        0   
675     0     1                        1                        0   
677     0     1                        1                        0   
679     0     1                        0                        1   
680     0     1                        1                        0   
681     0     1                        1                        0   
682     0     1                        1                        0   
683     0     1                        1                        0   
684     0     1                        1                        0   
685     0     1                        1                        0   
686     1     0                        1                        0   
687     0     1                        1                        0   
688     0     1                        1                        0   
689     1     0                        1                        0   
690     1     0                        0                        1   
691     0     1                        1                        0   
692     0     1                        1                        0   
693     1     0                        1                        0   
694     0     1                        1                        0   
695     0     1                        0                        1   
696     0     1                        1                        0   
697     0     1                        1                        0   
698